apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: couchdb-service
  name: couchdb-service
spec:
  replicas: {{ .Values.services.couchdb.replicaCount }}
  selector:
    matchLabels:
      io.kompose.service: couchdb-service
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: couchdb-service
    spec:
      containers:
      - env:
        - name: COUCHDB_PASSWORD
          value: {{ .Values.services.couchdb.password | quote }}
        - name: COUCHDB_USER
          value: {{ .Values.services.couchdb.user | quote }}
        image: ibmcom/couchdb3
        imagePullPolicy: ""
        startupProbe:
          exec:
            command:
            - curl 
            - -u 
            - "{{ .Values.services.couchdb.user }}:{{ .Values.services.couchdb.password}}"
            - -X 
            - PUT 
            - "{{ .Values.services.couchdb.host }}:5984/_users"
            - '&&'
            - curl 
            - -u
            - "{{ .Values.services.couchdb.user }}:{{ .Values.services.couchdb.password}}"
            - -X 
            - PUT 
            - "{{ .Values.services.couchdb.host }}:5985/_replicator"
          initialDelaySeconds: 5
          periodSeconds: 5
        name: couchdb-service
        ports:
        - containerPort: {{ .Values.services.couchdb.port }}
        resources: {}
        volumeMounts:
        - mountPath: /opt/couchdb/data
          name: couchdb3-data
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: couchdb3-data
        persistentVolumeClaim:
          claimName: couchdb3-data
status: {}
